### ISSUE TITLE
EAN 13 with leading 0 is being interpreted with UPCA

### ISSUE THREAD

**Issue by GAMELEIRA** [ionic-team/capacitor-barcode-scanner#31]
My app can scan both EAN-13 and UPC-A barcodes. When I have a valid barcode with a leading 0, the 0 is being removed, and it becomes a valid UPC-A code.

Attached is an example of barcodes that are valid for this scenario
<img width="538" alt="Captura de Tela 2024-10-22 às 11 35 00" src="https://github.com/user-attachments/assets/8961730e-61df-43ef-a335-9f632587c821">

**Comment by terryburton** [comment]
Note that the bar patterns are the same in both of your EAN-13 and UPC-A symbols. That is because the design of EAN-13 extends UPC-A with an additional prefix digit which is accomplished by selectively mirroring the groups of bar patterns on the left hand side of the symbol. A "0" prefix in EAN-13 is produced when no mirroring has occurred, i.e. the bar pattern is identical to UPC-A.

The transfer protocol for EAN-13, UPC-A and UPC-E is to transmit a 13-digit code using a common symbology identifier. The intent is to purposefully treat them as indistinguishable symbols — going so far as to reverse the zero-suppression of UPC-E — because the scanned data belongs to a common number system (GTIN-13). It is never correct to differentiate the scan data based on whether a EAN-13, UPC-A or UPC-E carrier is used.

Note that EAN-8 is technically a separate number system (GTIN-8), so the transfer protocol states that 8 digits shall be returned under a dedicate symbology identifier. However, GS1 later chose to reserve the corresponding zero-prefixed range within the GTIN-13 system so that an equivalence can be made between GTIN-13 and GTIN-8 in many circumstances.

Issues arise because many barcode scanning libraries do not even attempt to honour the transfer protocol defined by the fundamental barcode symbology specifications, and instead present an API that places the onus on the application to make the necessary equivalences.

**Comment by GAMELEIRA** [comment]
Hi Terry! How are you?

Thank you very much for the clarification! So, this is not a problem but rather a rule? Do all readers that do not have a predefined type of barcode, when reading an EAN-13, interpret it as UPC-A? Do you think the best solution would be to address this scenario with the user? For example, by adding a modal for them to choose whether the code has a leading '0' or not? This is important because they may have registered items in different formats, and the presence of the leading '0' can make a difference in searches.

**Comment by terryburton** [comment]
> This is important because they may have registered items in different formats.

In open supply chains, users do not register items against specific barcode formats. They are assigned a numeric prefix by their local registration authority and may then generate GTINs subordinate to their prefix. The carrier (EAN-13 vs UPC-A) used to represent their GTINs is irrelevant.

Mobile decoder libraries generally do not respect industry standards. Either the authors of these libraries have never read the symbologies standards or they have chosen  to ignore them because the behaviour is clearly specified. They tend to design APIs that present irrelevant information to the application and hide critical information.

In closed applications, a user may do whatever they like — they are on their own. However they should be aware that if they were to scan either of your example barcodes above using a standards compliant barcode scanner, it would correctly return `]E00725272730706`. I'm not going to go further into why this is the case. You can read ISO/IEC 15420 to find out the details.

**Comment by GAMELEIRA** [comment]
Hi Terry! How are you?

Thank you very much for the clarification! I will closed this issue with this explanation! Thank u again!

**Comment by axxel** [comment]
> Either the authors of these libraries have never read the symbologies standards or they have chosen to ignore them because the behaviour is clearly specified.

Thanks @terryburton for pointing me to this discussion. I came to the conclusion that `zxing-cpp` needs to change its behaviour (inherited from Java ZXing) to comply with the spec just yesterday. I became aware of the issue already 3 years ago but I guess I was too intimidated by the "authority" of the original ZXing project back then - not anymore... ;). `zxing-cpp` behaved just like described in the OP until today and from now on will return `]E00725272730706` for both symbols.
